# Naive Bayes

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le = LabelEncoder()

In [7]:
df['Sex'] = le.fit_transform(df['Sex'])

In [8]:
df['Embarked'] = le.fit_transform(df['Embarked'])

In [9]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         2  
1          PC 17599  71.2833   C85         0  
2  STON/O2. 3101282   7.9250   NaN         2  
3            113803  53.1000  C123         2  
4            373450   8.0500   NaN         2

In [10]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [11]:
df.shape

(889, 12)

In [12]:
df = df.drop(['Cabin'],axis=1)

In [13]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare  Embarked  
0         A/5 21171   7.2500         2  
1          PC 17599  71.2833         0  
2  STON/O2. 3101282   7.9250         2  
3            113803  53.1000         2  
4            373450   8.0500         2

# Model 1

In [29]:
Y = df['Survived']
X = df.drop(['Survived','PassengerId','Name','Ticket'],axis=1)


In [30]:
Y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [31]:
X.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    1  22.0      1      0   7.2500         2
1       1    0  38.0      1      0  71.2833         0
2       3    0  26.0      0      0   7.9250         2
3       1    0  35.0      1      0  53.1000         2
4       3    1  35.0      0      0   8.0500         2

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=0)

In [34]:
X_train

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
350       1    1  45.0      0      0  35.0000         2
124       3    1  12.0      1      0  11.2417         0
577       3    0  45.0      1      0  14.4583         0
422       3    0  28.0      1      1  14.4000         2
118       3    0   2.0      4      2  31.2750         2
..      ...  ...   ...    ...    ...      ...       ...
835       3    1  45.0      0      0   8.0500         2
192       2    1   3.0      1      1  26.0000         2
629       1    1  80.0      0      0  30.0000         2
559       3    1  45.0      0      0   7.7500         1
684       2    1  25.0      1      2  41.5792         0

[622 rows x 7 columns]

In [35]:
X_test

Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
14        3    0  14.0      0      0    7.8542         2
158       3    1  45.0      8      2   69.5500         2
762       1    0  36.0      1      2  120.0000         2
740       1    1  36.0      1      0   78.8500         2
482       3    0  63.0      0      0    9.5875         2
..      ...  ...   ...    ...    ...       ...       ...
619       3    1  27.0      1      0   14.4542         0
820       3    1  27.0      0      0    8.6625         2
64        3    1  45.0      1      1   15.2458         0
882       3    1  25.0      0      0    7.0500         2
52        1    0  49.0      1      0   76.7292         0

[267 rows x 7 columns]

In [36]:
from sklearn.naive_bayes import *

In [37]:
clf = BernoulliNB()

In [38]:
y_pred = clf.fit(X_train,y_train).predict(X_test)

In [39]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [40]:
accuracy_score(y_test,y_pred,normalize=True)

0.7715355805243446

In [41]:
confusion_matrix(y_test,y_pred)

array([[131,  26],
       [ 35,  75]], dtype=int64)

# Model 2

In [43]:
Y = df['Pclass']
X = df.drop(['Pclass','PassengerId','Name','Ticket'],axis=1)


In [44]:
Y.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [45]:
X.head()

Survived  Sex   Age  SibSp  Parch     Fare  Embarked
0         0    1  22.0      1      0   7.2500         2
1         1    0  38.0      1      0  71.2833         0
2         1    0  26.0      0      0   7.9250         2
3         1    0  35.0      1      0  53.1000         2
4         0    1  35.0      0      0   8.0500         2

In [46]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=0)

In [47]:
y_pred = clf.fit(X_train,y_train).predict(X_test)

In [48]:
accuracy_score(y_test,y_pred,normalize=True)

0.5917602996254682

In [49]:
confusion_matrix(y_test,y_pred)

array([[ 30,   8,  32],
       [  9,  10,  30],
       [ 24,   6, 118]], dtype=int64)

# Model 3

In [63]:
Y = df['Embarked']
X = df.drop(['Embarked','PassengerId','Name','Ticket'],axis=1)


In [64]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=0)

In [65]:
y_pred = clf.fit(X_train,y_train).predict(X_test)

In [66]:
accuracy_score(y_test,y_pred,normalize=True)

0.7340823970037453

In [67]:
confusion_matrix(y_test,y_pred)

array([[  0,   0,  49],
       [  0,   0,  22],
       [  0,   0, 196]], dtype=int64)

# Model 4

In [68]:
Y = df['Sex']
X = df.drop(['Sex','PassengerId','Name','Ticket'],axis=1)


In [69]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=0)

In [70]:
y_pred = clf.fit(X_train,y_train).predict(X_test)

In [71]:
accuracy_score(y_test,y_pred,normalize=True)

0.7453183520599251

In [72]:
accuracy_score(y_test,y_pred,normalize=True)

0.7453183520599251

In [73]:
confusion_matrix(y_test,y_pred)

array([[ 49,  49],
       [ 19, 150]], dtype=int64)