#Numpy Cheat Sheet

In [1]:
import numpy as np

#Creating Array

In [2]:
# 1D array
np.array([1,2,3,4,5])


array([1, 2, 3, 4, 5])

In [3]:
#2D array
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

b = np.array( [ (1.5,2,4) , (4,5,6) ] ,dtype=float )
print(b)


[[1 2 3 4]
 [5 6 7 8]]
[[1.5 2.  4. ]
 [4.  5.  6. ]]


#Initial Placeholders
##(some methods)

###1. Arrange
creates an array of evenly spaced values

In [4]:
#last value is not included
d = np.arange(0,10)
print(d)

d1 = np.arange(0,10,3)
print(d1)

[0 1 2 3 4 5 6 7 8 9]
[0 3 6 9]


###2. Zeros
create an arrays of zeros

In [5]:
# 1D array
a = np.zeros(5,dtype=int)
# print(a)
# np.zeros(5)


#2D array
np.zeros((2,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

###3.Ones 
create an arrays of ones

In [6]:
#1D
a = np.ones(5)
print(a)

#2D
np.ones((2,5),dtype=np.int8)
# np.ones((2,5))


[1. 1. 1. 1. 1.]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

###4.Eye
create and identity matirx

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###5. Linspace
create an array of evenly space values

In [8]:
np.linspace(0,50,11,dtype=int)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

###6. Random 
create an array with random values

In [9]:
#1D
np.random.random(5)

#2D
a =np.random.rand(2,3)
print(a,"\n")

#another way
a1 = np.random.random((2,3))
print(a1,"\n")

#By using randint =>> this will print any random no between 0 to 3 (3 included)
rand1 = np.random.randint(3)
print(rand1,'\n')

rand2 = np.random.randint(1,10) #10 excluded
print(rand2,'\n')

#If we want to insert random integer to array then we can do like below
my_arr = np.random.randint(1,10,6)

print(my_arr,'\n')

#MAX and MIN

max = my_arr.max()
min = my_arr.min()
print("Max : ", max)
print("Min : ", min,'\n')

#To return the index of max and min element
max_index = my_arr.argmax()
min_index = my_arr.argmin()

print("Max_Index :",max_index)
print("Max_Index :",min_index,'\n')

#Reshaping
#convert 1d array to 2D
# [6 3 1 6 5 2] 

new_arr = my_arr.reshape(2,3)
print(new_arr)
print('\n')


[[0.43594431 0.93414394 0.80541402]
 [0.27995966 0.08138133 0.49910454]] 

[[0.20791594 0.14659831 0.20573165]
 [0.80280679 0.63039416 0.63261297]] 

2 

8 

[2 7 7 8 1 6] 

Max :  8
Min :  1 

Max_Index : 3
Max_Index : 4 

[[2 7 7]
 [8 1 6]]




##Indexing

In [12]:
print(my_arr)
my_arr[2] = 33
print(my_arr)

[ 2  7 33  8  1  6]
[ 2  7 33  8  1  6]


## Creating Copy

In [13]:
my_arr1 = my_arr.copy()
print(my_arr1)

[ 2  7 33  8  1  6]


##2D Arrays 

In [21]:
array2d = np.array( [ (1,2,3) , (4,5,6) , (6,78,7) ] ) 
print(array2d,'\n')

#access a element
print(array2d[1][1],'\n')

#another way
print(array2d[1,1],'\n')


[[ 1  2  3]
 [ 4  5  6]
 [ 6 78  7]] 

5 

5 



##Slicing

In [30]:
print(array2d,'\n')

print(  array2d[1:] )
print('\n')

print(  array2d[1:,1:] )
print('\n')

print(   array2d[0:2]    )
print('\n')

print( array2d[::-1] )

[[ 1  2  3]
 [ 4  5  6]
 [ 6 78  7]] 

[[ 4  5  6]
 [ 6 78  7]]


[[ 5  6]
 [78  7]]


[[1 2 3]
 [4 5 6]]


[[ 6 78  7]
 [ 4  5  6]
 [ 1  2  3]]


##Comparison

In [36]:
print(my_arr)
print('\n')

#Return true and false 
arr = my_arr>2
print(arr)
print('\n')

#returns the value 
arr1 = my_arr[my_arr>2]
print(arr1)
print('\n')



[ 2  7 33  8  1  6]


[False  True  True  True False  True]


[ 7 33  8  6]




##Operations

In [48]:
print(my_arr)
print('\n')
print(my_arr1)
print('\n')

#Addition
print("Addition")
add_two_arr = my_arr + my_arr1
print(add_two_arr)
print('\n')

#Subtraction
print("Subtraction")
sub_two_arr = my_arr - my_arr1
print(sub_two_arr)
print('\n')

#Multiplication
print("multiplication")
Mul_two_arr = my_arr * my_arr1
print(Mul_two_arr)
print('\n')

#Divide
print("divide")
div_two_arr = my_arr / my_arr1
print(div_two_arr)
print('\n')

#add 10 to all
a = my_arr+10
print(a)
print('\n')
#Similar for m,d,s

#Square root
sq_arr = np.sqrt(my_arr)
print(sq_arr)
print('\n')



[ 2  7 33  8  1  6]


[ 2  7 33  8  1  6]


Addition
[ 4 14 66 16  2 12]


Subtraction
[0 0 0 0 0 0]


multiplication
[   4   49 1089   64    1   36]


divide
[1. 1. 1. 1. 1. 1.]


[12 17 43 18 11 16]


[1.41421356 2.64575131 5.74456265 2.82842712 1.         2.44948974]




##Aggregate Functions

In [56]:
print(my_arr)
print('\n')

#Sum
sum_arr = my_arr.sum()
print(sum_arr)
print('\n')

#Min
min_arr = my_arr.min()
print(min_arr)
print('\n')

#Max
max_arr = my_arr.max()
print(max_arr)
print('\n')

#mean
mean_arr = my_arr.mean()
print(mean_arr)
print('\n')

#same for mean median and var

# >>> b.cumsum(axis=1) Cumulative sum of the elements 
# >>> a.mean() Mean
# >>> b.median() Median
# >>> a.corrcoef() Correlation coefficient
# >>> np.std(b) standard deviation

[ 2  7 33  8  1  6]


57


1


33


9.5


