#1. Create a 3x3x3 array with random values¶


In [1]:
import numpy as np

a = np.empty((3,3))
print(a)

[[3.96504835e-316 3.45544493e-316 0.00000000e+000]
 [3.96512345e-316 2.59007472e-316 2.47032823e-323]
 [2.54768670e+179 2.59494502e-316 4.94065646e-324]]


#2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal¶

In [2]:
a = np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [45]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#3.Create a 8x8 matrix and fill it with a checkerboard pattern¶


In [5]:
a = np.zeros((8,8))

In [6]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
for i in range(len(a)):
  for j in range(0,len(a),2):
    a[i][j]=1

In [8]:
a


array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#4. Normalize a 5x5 random matrix¶


In [9]:

b = np.ones((5,5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
for i in  range(len(b)):
  for j in range(len(b)):
    b[i][j]=0
  

print(b)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#5. How to find common values between two arrays?¶


In [11]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[3,2,1],[6,5,4],[9,8,7]])

print(a)
print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [12]:
for i in range(len(a)):
  for j in range(len(b)):
    if(a[i][j]==b[i][j]):
      print(a[i][j])

2
5
8


#6.How to get the dates of yesterday, today and tomorrow?¶


In [13]:
today = np.datetime64('today','D')
print("Today",today)
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print('Tomorrow', tomorrow)
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
print("yesterday",tomorrow)


Today 2020-07-27
Tomorrow 2020-07-28
yesterday 2020-07-28


#7. Consider two random array A and B, check if they are equal¶


In [14]:
a = np.array([[3,2,1],[6,5,4],[9,8,7]])
b = np.array([[3,2,1],[6,5,4],[9,8,7]])

print(a)
 
print(b)
# a = a+b
# print(a)
col = a.shape[1]
row = a.shape[0]
elements = col*row
print(elements)
print(len(a))

[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
9
3


In [15]:
count=0
if a.shape==b.shape:
  for i in range(len(a)):
    for j in range(len(b)):
      if(a[i][j]==b[i][j]):
        count = count+1
  
if count==elements:
    print("Equal")
else :
  print("No equal")


  



Equal


#8.Create random vector of size 10 and replace the maximum value by 0¶


In [16]:
v  = np.array([1,2,3,4,5,6,7,8,9,0])
max_ele = v.max()

print("Before replacing",v)

for i in range(len(v)):
  if v[i]==max_ele:
    v[i]=0

print("After replacing",v)


Before replacing [1 2 3 4 5 6 7 8 9 0]
After replacing [1 2 3 4 5 6 7 8 0 0]


#9. How to print all the values of an array?¶


In [17]:
b

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [18]:
for i in range(len(b)):
  for  j in range(len(b)):
    print(b[i][j],end=" ")


3 2 1 6 5 4 9 8 7 

#10.Subtract the mean of each row of a matrix¶


In [19]:
b


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [20]:
mean_val = b.mean()
mean_val

5.0

In [21]:
for i in range(len(b)):
  for j in range(len(b)):
    b[i][j] = b[i][j]-mean_val

b

array([[-2, -3, -4],
       [ 1,  0, -1],
       [ 4,  3,  2]])

#11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?¶


In [47]:
v

array([1, 2, 3, 4, 5, 6, 7, 8, 0, 0])

In [48]:
for i in range(len(v)):
  v[i] +=1

v

array([2, 3, 4, 5, 6, 7, 8, 9, 1, 1])

#12.How to get the diagonal of a dot product?



In [22]:
print(a)
print(b)

[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[-2 -3 -4]
 [ 1  0 -1]
 [ 4  3  2]]


In [23]:
dot_product = a.dot(b)
print(dot_product)

[[  0  -6 -12]
 [  9  -6 -21]
 [ 18  -6 -30]]


In [24]:
for i in range(len(dot_product)):
  for j in range(len(dot_product)):
    if i==j:
      print(dot_product[i][j])

0
-6
-30


#13.How to find the most frequent value in an array?¶


In [25]:
x = np.random.randint(1,10,30)
print(x)
len(x)

print(np.bincount(x).argmax())


[9 1 8 5 6 8 9 5 7 2 3 5 5 8 9 8 3 2 1 5 5 8 3 7 9 6 8 2 5 9]
5


#14.How to get the n largest values of an array



In [41]:
y = np.array([1,2,3,4,5,6,7])
y
print(y[:-3])

[1 2 3 4]


In [44]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
print(x)
n = 3
print (x[np.argsort(x)])
print (x[np.argsort(x)[-n:]])


Original array:
[0 1 2 3 4 5 6 7 8 9]
[9 8 0 5 6 4 2 7 3 1]
[0 1 2 3 4 5 6 7 8 9]
[7 8 9]


In [30]:
nLargest(3)

7


#15.How to create a record array from a regular array?¶


In [46]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])


(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
